import Layout from "../components/common/Layout";
import '../styles/Home.scss';


const Home = () => {
  return ( 
    <Layout>

      <div className="Home">
        <h2>Home</h2>

        <div className="Paragraphs">
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti labore dolores hic accusamus autem totam facilis iusto quasi, optio alias similique? Culpa autem exercitationem unde delectus itaque harum eligendi vitae blanditiis nam impedit, aspernatur a nihil error tenetur quidem sunt ipsum mollitia rem nemo odit? Voluptas recusandae nobis excepturi doloremque rerum, dolorem fugit atque veniam reprehenderit, dolores sint quae dolorum est porro animi cumque similique quod. Non suscipit omnis ab. Corrupti cum provident, incidunt sed maxime id neque nisi magnam error, debitis laborum fugit veniam voluptatum iusto, assumenda nam unde nemo tempora consequuntur? Aliquid explicabo maxime dignissimos, vel a impedit!</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum nemo ipsa autem, mollitia, eligendi impedit eveniet, possimus deleniti ad adipisci! Est a voluptate cum temporibus, quaerat vel quia veritatis?</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis molestias, est incidunt nobis animi vero quas id voluptatum praesentium voluptas consequuntur, ab nostrum repellat ratione porro repudiandae dolor totam earum delectus hic doloribus quia! Corrupti eveniet molestiae harum iste minus quidem inventore vero placeat labore ex cumque illo adipisci in optio nihil molestias recusandae veniam mollitia id eligendi, obcaecati sed iure qui quo? Deleniti quam accusantium dolorem sunt est fuga pariatur! Aliquam aut culpa quia officia saepe, eum ipsum in mollitia ullam earum quibusdam suscipit esse recusandae quisquam odio voluptatem aperiam. Quibusdam, sed. Ut voluptas ipsum, ea est necessitatibus repudiandae sint facere, velit placeat id sapiente recusandae! Sit unde earum porro quod voluptatum ducimus consectetur doloribus officia cupiditate illo pariatur eum nobis inventore at neque sint quis, natus error. Harum, hic ad qui et temporibus impedit voluptates sint est quia iure voluptatem non nobis sapiente. Libero reprehenderit voluptatem minima, praesentium reiciendis sed assumenda iure atque consequatur maxime. Facilis eum inventore dolor ea minima, ipsum ex sunt dignissimos ipsa dolorem quia rerum rem totam dolorum eaque error quae vero et illum eos obcaecati. Blanditiis, sapiente provident iure debitis architecto placeat expedita quas animi rerum praesentium, dolores maxime repudiandae quasi ratione id nulla! Laboriosam distinctio nesciunt provident hic nisi, natus totam quaerat sequi qui veritatis aliquam obcaecati labore, corporis officia animi dolores perspiciatis autem illum inventore ipsum. Nostrum, suscipit veniam laudantium laboriosam possimus inventore non perferendis itaque fugit quo alias perspiciatis quisquam ullam quis omnis totam, reiciendis dignissimos ea nesciunt vero qui tenetur tempora vel. Deleniti, ipsam, corrupti amet soluta veniam at maxime est iure ipsa obcaecati aperiam quae assumenda fugiat explicabo eius excepturi praesentium voluptatibus magni possimus iusto voluptate. Consequatur accusamus esse accusantium quod ab non facilis quam unde magnam soluta eveniet, ratione a doloremque blanditiis tenetur animi dolore alias. Impedit.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam quis voluptates pariatur perspiciatis impedit ut, fugit officia harum, laborum eum sapiente repudiandae veniam. Nemo, laboriosam deleniti ratione, saepe iure tempora, sequi cumque tempore odio earum veritatis nam ipsa sit atque! Dignissimos totam necessitatibus pariatur, consectetur nemo eos, explicabo molestiae, aliquam harum saepe ipsa officia libero voluptate quibusdam optio hic. Deserunt veniam ipsum optio repellendus, adipisci, nesciunt ut, quas neque similique facere officia dolorem minus. Nemo velit asperiores dolor iusto aliquid repudiandae impedit assumenda, necessitatibus illo quisquam error odit. Aliquam ratione enim, maxime pariatur perferendis velit dolorem harum vitae totam ad nihil. Maiores labore dolorem aut quo ea accusamus quisquam veritatis atque reiciendis, corporis maxime impedit exercitationem animi nostrum. Accusantium laboriosam nam soluta blanditiis excepturi, eos vel nesciunt illo ad eius possimus repellat suscipit consequatur voluptatum provident non saepe maiores ea a unde natus rerum officia repellendus beatae? Quisquam blanditiis optio dolorem? Veritatis atque iusto nostrum, velit quo consequuntur numquam vel sed ab, totam quae in corporis asperiores possimus hic doloremque sapiente. Sed id, earum molestiae neque temporibus facilis laborum odio nihil? Deserunt perferendis sequi alias, libero praesentium similique ducimus impedit nihil corporis quos placeat aperiam iste numquam optio, possimus tempore. Repudiandae esse quae explicabo recusandae, consequuntur beatae voluptates animi obcaecati sit dolorum. Nulla perspiciatis nam molestiae illum culpa corporis dolores.</p>
        </div>

      
      </div>

    </Layout>
   );
}
 
export default Home;